### ISSUE TITLE
Web Projects Build Support

### ISSUE THREAD

**Issue by Nirmal4G** [onovotny/MSBuildSdkExtras#76]
Things that could not be completed in #56 and #80

- [ ] WCF (Closes #)
- [ ] WFF (Closes #59)
- [ ] ASP.NET (Closes #60)

_will update after previews of the latest code_

**Comment by onovotny** [comment]
Closing as old.

**Comment by jzabroski** [comment]
@Nirmal4G @clairernovotny While this issue is closed, I'm curious if MSBuild.Sdk.Extras supports ASP.NET Classic?  In #60, @clairernovotny explained the blocking issue was related to launching IIS Express and attaching the debugger via MSBuild, and that in order for this to work, it has to be part of the core SDK support (I'm not clear on that assumption/statement and why it can't be added in a way similar to AttachToAnything Visual Studio plug-in works - I've created similar hooks for debugging PowerShell binary cmdlet projects).

**Comment by Nirmal4G** [comment]
VS Team is currently working to support legacy projects opening in CPS.

I have WFF/ASP/WPF limited support in my fork of this sdk for my own projects. It's hacky and I don't recommend anyone to use it in production projects.

However, if you want to cleanup the `ItemGroup`s in the project file. You can use my [`MSBuild.NET.DefaultItems`](/nirin/msbuild-sdks#msbuild.net.defaultitems).

**Comment by jzabroski** [comment]
@Nirmal4G Whoa, MSBuild.NET.DefaultItems sounds interesting.

Can I ask you a few questions for my own education?

1. Before today, I always assumed that the SDKs were limited to the ones mentioned in Microsoft Docs at [.NET Core project SDKs](https://docs.microsoft.com/en-us/dotnet/core/project-sdk/overview)
2. The MSBuild.NET.DefaultItems seems to point a way forward for me to create my own SDK fairly easily.
3. In particular, as co-maintainer of FluentMigrator, it would be nice for "Database migration assemblies" for people to set an Sdk="FluentMigrator.Sdk" which will change the out-of-the-box auto-globbing rules of the `Microsoft.Net.Sdk` - is that possible and am I starting to understand the possiblities of this project and your fork here?
4. Is this project still actively maintained - or should I be following your fork instead?  Your last commit is within the last month, vs. this project last updated >6 months ago.

**Comment by Nirmal4G** [comment]
**This is active, always use this one over mine.**

Mine's not official open source project. They are ideas, I use in my own projects. That's also the reason they are not documented yet.

But my colleagues have expressed interest in default globbing, so I created it for them. Again, not for production!!
